INSERT INTO users VALUES (1, 'Konrad', 'some1@gmail.com', 'Konrad', 'konrad');
INSERT INTO users VALUES (2, 'Karol', 'alex@yahoo.com', 'Karol', 'querty');
INSERT INTO users VALUES (3, 'Admin', 'joel@gmail.com', 'admin', 'admin');
INSERT INTO books VALUES (1, 'Spring w akcji', 'Weig', 400, 'ISBN99');
INSERT INTO books VALUES (2, 'Czysty kod', 'Mark', 600, 'ISBN12');
INSERT INTO books VALUES (3, 'Java 6 EE', 'Nowak', 250, 'ISBN89');
INSERT INTO books VALUES (4, 'Hibernate', 'Weig', 300, 'ISBN97');
INSERT INTO books VALUES (5, 'Java X', 'Carl', 700, 'ISBN945');
INSERT INTO books VALUES (6, 'Spring MVC', 'Marks', 450, 'ISBN00');
INSERT INTO books VALUES (7, 'Thymeleaf', 'Weig', 300, 'ISBN27');
INSERT INTO books VALUES (8, 'MySQL', 'Weig', 340, 'ISBN97');
INSERT INTO books VALUES (9, 'Spring Security', 'Weig', 460, 'ISBN11');
INSERT INTO books VALUES (10, 'Spring Data', 'Carl', 390, 'ISBN22');